### ISSUE TITLE
net.rim.vm.Process was not published in blackberry sdk 6

### ISSUE THREAD

**Issue by SeanWang** [blackberry/WebWorks#1]
in file and line:
framework/src/blackberry/web/widget/Widget.java 140
framework/src/blackberry/web/widget/Widget.java 145
there are codes:
net.rim.vm.Process.waitForIdle(); and net.rim.vm.Process.waitForIdle(30000);
it can't pass compiling, because net.rim.vm.Process can't be resolved.
net.rim.vm.Process can't be found in documents of sdk 6.0 also.

**Comment by tneil** [comment]
We have one of the guys taking a look at this.. hopefully we will have some more comments soon

**Comment by EricLeiLi** [comment]
It was a known issue in our previous version: net.rim.vm.Process is a RIM internal API.
For now, a simple walkaround is to comment out these 2 lines in Widget.java
We will fix it in the next update.

**Comment by jamespaulmuir** [comment]
I have updated the code in Widget.java in my pull request (issue #2 ) that shows how this method behaved in the BlackBerry web plug-in for eclipse v2.5

**Comment by ghost** [comment]
Thanks jamespaulmuir for the patch. I've pushed it to our git repo.
