### ISSUE TITLE
Webworks blackberry.ui.menu.open() opening menu at top right

### ISSUE THREAD

**Issue by wmwragg** [blackberry/WebWorks#124]
I am overiding the Blackberry menu button, to allow me to do various things before opening the menu, I then make a call to blackberry.ui.menu.open() to open the menu, but instead of opening at the bottom left, it opens the menu at the top right.

I am using WebWorks SDK for Smartphones 2.3.1.5 on a Bold 9790 with OS 7.0.0 Bundle 2356 (v7.0.0.557, Platform 9.16.0.67)

**Comment by okComputer85** [comment]
The same for me...did you find any solution about that?

**Comment by wmwragg** [comment]
No, I'm afraid not. Apparently Blackberry have said that it is a bug in webworks, but they don't seem to be fixing it. The only real solution is to make your own menu, which sucks.

**Comment by wmwragg** [comment]
Closing this, as nothing is going to be done about it, and I no longer care, as Blackberry don't seem to either
