### ISSUE TITLE
HTML5 database (possible) issue

### ISSUE THREAD

**Issue by bglowDragosh** [blackberry/WebWorks#130]
[issue moved to: https://github.com/blackberry/BB10-WebWorks-Framework/issues/541 ]

I am using a HTML5 database for a BB10 app. I used a creationCallback function as an argument to the constructor:

db = openDatabase("myDBname", '1.0', 'myDBdisplayName', 50 \* 1024, firstAppRun());

From what I read in the documentation, the firstAppRun() function in my example should only get triggered the first time my app is loaded, when it first creates the database. However, it gets triggered every time I restart the app.

I'm guessing I may have messed up somewhere in the code, but I wanted to ask if anyone else experienced this issue (looked it up, but haven't seen any posts on this).

**Comment by kwallis** [comment]
Hi there.  this repo is actually for our BBOS version of the WebWorks Framework.  Could you please open this issue in the https://github.com/blackberry/BB10-WebWorks-Framework/issues repo?

**Comment by bglowDragosh** [comment]
Thanks for the heads up and the link! Will post it there now.
