### ISSUE TITLE
Access to the Media Keys ("MediaKeyWatcher")

### ISSUE THREAD

**Issue by dotcom84** [blackberry/WebWorks#133]
This is a feature request to get WebWorks access to the device's media keys. It is already available in Cascades as described here: https://developer.blackberry.com/cascades/reference/bb__multimedia__mediakeywatcher.html

Media Keys might be handy for a number of tasks. In my case I'd like to use them in order to control the volume of remote systems.

**Comment by kwallis** [comment]
Thanks for the report.  I have moved it here:
blackberry/BB10-WebWorks-Framework/issues/577
