### ISSUE TITLE
Get notified of Incoming Calls

### ISSUE THREAD

**Issue by dotcom84** [blackberry/WebWorks#134]
This is feature request for an event listener, that allows WebWorks developers to handle incoming calls (including the number, if permission is given by the user).
This feature is available to native developers as described here: https://developer.blackberry.com/cascades/reference/device_and_communication_phone.html

I'd like to handle incoming calls by for example automatically pausing media playback in my app or muting a remote system.

**Comment by kwallis** [comment]
Would you like me to move this one as well? ;)

**Comment by dotcom84** [comment]
Sorry, obviously I was too fast posting. Sure, please move it. I've put my third feature request in the right place...

**Comment by kwallis** [comment]
Tracked here:
blackberry/BB10-WebWorks-Framework/issues/579
