### ISSUE TITLE
WebWorks does not degrade gracefully when run without Ripple

### ISSUE THREAD

**Issue by jonwebb** [blackberry/WebWorks#137]
WebWorks should not _require_ the use of Ripple, but degrade gracefully. Ripple is often too buggy to use in production, therefore other tools must still be usable. WebWorks should still fire the ready event, but offer an opportunity to detect API availability. The app can then choose whether or not to enable certain features.

Simply including the webworks .js throws errors when run in plain Chrome. Should not be dependent on localhost:8472.

**Comment by kwallis** [comment]
Hi Jon.  Thanks for the feedback.  I agree that this would be a great feature.  Moving forward on BlackBerry 10 WebWorks will be based on Apache Cordova, so this would be better placed as a feature request against Cordova, where we could then just get it within WebWorks.  I would encourage you to inquire about this on the Cordova mailing list. That said, in many respects this is a broader discussion for web runtimes and browsers in general that I know some leading web figures are starting talks around.
