### ISSUE TITLE
Release Tablet SDK Code

### ISSUE THREAD

**Issue by pnewhook** [blackberry/WebWorks#4]
I'd like to see the tablet SDK properly released. I realize this is on the roadmap, but it hasn't happend yet and I'd like to give you gentle nudge.

With the simulator being pretty restrictive and not yet supporting all the APIs (camera, any other installed apps) I'm doing a lot of my development directly in a browser. I'm trying to build a browser "bridge" that lets me mock the playbook's actual interactions and it would be helpful to see a real release with the WebWorks sdk removed from the unnecessary adobe air files.

**Comment by tneil** [comment]
Hi pnewhook,

By properly released do you mean out of beta?

**Comment by pnewhook** [comment]
No, a release of the beta code on GitHub is fine. When I say 'properly' I'm referring to the fact that the .js files are available in the SDK for inspection, but they're not formally part of the open source release.

In fact, I'd say it's preferred to release and document the beta SDK as it allows us to potentially comment on the API and offer changes before the API is 100% finalized. If nothing else, I'd really appreciate a deep dive on how the WebWorks SDK works. I've been examining how the JavaScript is calling native functionality through an ActionScript bridge, but I'd love to hear some explanations from the dev team.

**Comment by pnewhook** [comment]
whoops, shouldn't have closed this issue.

**Comment by tneil** [comment]
Hi pnewhook,

You'll notice that just this morning we started on creating the repository for the PlayBook source code.  Your timing is pretty good :)

We are starting off with getting the wiki up and rolling and the source code should be up in a couple of days.

I'll also try and see if we can get some more architectural information up on the wiki to better explain how things work.

**Comment by pnewhook** [comment]
sounds good, thanks.
