### ISSUE TITLE
bb widget sdk setup.exe mirror?

### ISSUE THREAD

**Issue by soemarko** [blackberry/WebWorks#6]
Does it exist? or at least a direct link to the file so I can use a download manager? the download is very slow and kept on failing halfway...

**Comment by tneil** [comment]
Hi soemarko,

We raised this concern with our web team and they have made some adjustments with our akamai mirror configuration.  Give it a try and see if it now solves your issue.

**Comment by soemarko** [comment]
yep the server is working much better now.

thank you :)

**Comment by tneil** [comment]
That's great to hear!
