### ISSUE TITLE
Packager refuses to pack dojo bas files with "_" in file name

### ISSUE THREAD

**Issue by sariputra** [blackberry/WebWorks#7]
with webworks framework claiming support for js frameworks like dojo jquery and sencha i dont think this should be happening??

**Comment by filmaj** [comment]
also "." characters mess the packager up.

**Comment by tneil** [comment]
in the upcoming release dashes and underscores should no longer be a problem

**Comment by tneil** [comment]
from what I have seen "." symbols cause issues when they are the first character in a file name.. have you seen otherwise?

**Comment by sariputra** [comment]
Wheb can we see the new release.. Also if we want to implement any changes on our own.. Instructions for packaging thw webworks is missing from readme in the git repository... That would really help

Thanks....

**Comment by tneil** [comment]
New release should be out in a week or two... I saw that the team had some external build instructions the other day.. I'll see where we are as far as posting them.

**Comment by tneil** [comment]
Underscores should now be supported in the Smartphone and PlayBook SDKs
