### ISSUE TITLE
Window.orientation incorrect.

### ISSUE THREAD

**Issue by genration** [blackberry/WebWorks#70]
When starting a webworks app in landscape mode on BB Torch 9800. Window.orientation reports as 0 despite the fact that it should report -90 or 90. After rotating to portrait and then back to landscape orientation is reported correctly.

**Comment by tneil** [comment]
Can you post the OS version number you are using on the torch.. e.g. 6.0.0.246

**Comment by genration** [comment]
Have since updated device software to latest and can't remember which version the device was using before. Sorry. It has been resolved it would seem in 6.0 bundle 2647. Have just retested. Can probably close. Other issue I opened to do with graphics rendering and layered HTML5 canvas is still active in the version mentioned above.
