### ISSUE TITLE
<rim:orientation> Support for smartphones

### ISSUE THREAD

**Issue by tneil** [blackberry/WebWorks#77]
Add the ability to lock the orientation for your application.  Implementation details are exactly the same as the [current support for PlayBook](https://bdsc.webapps.blackberry.com/html5/documentation/ww_developing/rim_orientation_element_1594186_11.html).

**Comment by muerl** [comment]
Oh!  I see what you meant Tim.  I thought you WROTE the support for this ;)

**Comment by tneil** [comment]
Yup... I wrote it and I think you found the pull request :)

**Comment by kwallis** [comment]
Pulled in...
