### ISSUE TITLE
bbwp builds debug bar file when -d is not present

### ISSUE THREAD

**Issue by MSohm** [blackberry/WebWorks#83]
BlackBerry WebWorks SDK for TabletOS 2.2.0.5

bbwp builds debug bar file when -d is not present 

If you use the instructions documented here to create an unsigned application: https://bdsc.webapps.blackberry.com/html5/documentation/ww_developing/compile_ww_app_for_tablets_1873322_11.html 

Quote: 
Package a unsigned application for tablets 

The BlackBerry WebWorks Packager uses the BlackBerry WebWorks archive test.zip file to produce an unsigned version of the compiled application. 

bbwp test.zip -o compiled 

In the manifest Application-Development-Mode is set to true. 

The prevents enterprise developers behind a proxy server from creating WebWorks applications because bbwp does not accept proxy parameters, which are required by barsigner to sign from behind a proxy server. They can be passed to blackberry-signer, however bbwp cannot be used to create an unsigned, non debug bar file that could be signed with blackberry-signer.

Steps to reproduce:  Run: bbwp yourApp.zip.
Expected Results:    An unsigned, non debug bar file is created.
Actual Results:  An unsigned, debug bar file is created.

**Comment by dmateescu** [comment]
Bases on the bug's description, this issue is for BB WebWorks for Tablet (not for smartphone). Do we still need to address it ? It will require a BB WW for Tablet release.

**Comment by MSohm** [comment]
Yes, this is for the Tablet release only.  It needs to be addressed.  Corporate developers still contact support about this issue.

**Comment by kwallis** [comment]
I will move it to the correct repo.

**Comment by kwallis** [comment]
Tracked now in the WebWorks-TabletOS repo:

https://github.com/blackberry/WebWorks-TabletOS/issues/48
