### ISSUE TITLE
Analytics API access from WebWorks

### ISSUE THREAD

**Issue by scunliffe** [blackberry/WebWorks#84]
I posted a request here http://supportforums.blackberry.com/t5/BlackBerry-WebWorks/Extending-the-BlackBerry-Analytics-API-to-JavaScript-in-WebWorks/td-p/1391865 in the forums, but this looks like it might be a better place.

I'd like to see access to the Analytics API http://docs.blackberry.com/en/developers/deliverables/34744/index.html?com/webtrends/mobile/analytics/package-summary.html from WebWorks on SmartPhones.  I'd be more than willing to help build such an extension too, just looking for a little guidance as to where to start.

**Comment by kwallis** [comment]
Thanks very much in your interest here!  What I might suggest, if you are willing to actually write some code for this, would be to do so and issue a pull request into our Community APIs repo here:

https://github.com/blackberry/WebWorks-Community-APIs

The readme there has some guidelines on how to get started etc.

Let us know if this is what you would be interested in doing.

**Comment by scunliffe** [comment]
Hi Ken,

Yes I am interested in writing some code for this... I was just under the impression that I needed certain "privileges" in order to contribute.

Likewise I wasn't sure if there was a quick HelloWorld example of how to create the "extension"... if not is there a particular extension that I should look to as an example?

**Comment by christianmarth** [comment]
Hi Ken,

I'm also interested in accessing analytics through the WebWorks javascript API and would be more than happy to work with you on building out code for this extension.

Let me know if you have a project I can fork and submit pull requests to.

**Comment by scunliffe** [comment]
I am still quite interested in this, I just got a bit sidetracked with building the actual app that I hope to use the analytics with ;-)

**Comment by kwallis** [comment]
For an overview of javascript extensions and how to create them, you can visit the section in our WebWorks site documentation:
http://developer.blackberry.com/html5/documentation/ww_developing/creating_and_using_a_js_extensiong_in_your_widget_1316872_11.html

A pretty good, simple example of an extension would be the smartphone notification extension:
http://github.com/blackberry/WebWorks-Community-APIs/tree/master/Smartphone/notification

For details on starting a community api extension, you can references the Readme in the main community api github repo here:
http://github.com/blackberry/WebWorks-Community-APIs

Thanks!

**Comment by kwallis** [comment]
I have moved this request to the Community APIs repo.  Please follow the new issue here:

http://github.com/blackberry/WebWorks-Community-APIs/issues/34

Thanks!
