### ISSUE TITLE
Contacts API missing property fields

### ISSUE THREAD

**Issue by jdnoprada** [blackberry/WebWorks#85]
**mobilePhone2** and **faxPhone2** could not be retrieved from contacts. Probably because they are commented out on :

https://github.com/blackberry/WebWorks/blob/master/api/pim/src/main/java/blackberry/pim/contact/ContactObject.java

**Comment by jeffheifetz** [comment]
Just for extra clarity I've attached a link to the area of the file https://github.com/blackberry/WebWorks/blob/master/api/pim/src/main/java/blackberry/pim/contact/ContactObject.java#L324

**Comment by jeffheifetz** [comment]
It seems like the reason is that these were removed is because they are internal only and not externally supported. They certainly aren't in the public API http://www.blackberry.com/developers/docs/5.0.0api/javax/microedition/pim/Contact.html

**Comment by jdnoprada** [comment]
I see. But will there be a possibility that it would be exposed? It's just that a part of my application includes a custom contact list which consists of phonebook contacts that have a mobile number and with the current implementation, since we could not check if there exists a mobile 2, that contact is not displayed on the list. With that said, is it possible to create a javascript just to expose this number?

**Comment by jdnoprada** [comment]
Oops, bumped into another problem on the following :
- OS 5.0.0.862 (Bundle 1446, Platform 5.1.0.175)
- OS 5.0.0.1036 (Bundle 1682, Platform 5.2.0.104)
- OS 5.0.0.846 (Bundle 1440, Platform 6.3.0.39)
  (These are all the device bundles I've tested my apps with, don't know if it's safe to say that it's for all OS5 bundles)

Seems that when a user has a Mobile 1 and Mobile 2 numbers, Mobile 2 is retrieved even if we're using the mobilePhone property.
Also, if a user has a Mobile 2 number (without Mobile 1), we were still able to retrieve a Mobile 2 number, again using the mobilePhone property.

This does not happen in OS 6 and OS 7 as of my latest testing which would be noticeable if the client checks on both OS's.

Should I file this as another issue?

Thanks for your assistance btw :)

**Comment by jeffheifetz** [comment]
It seems like these properties were made public in 6.0 - http://www.blackberry.com/developers/docs/6.0.0api/net/rim/blackberry/api/pdap/BlackBerryContact.html

Unfortunately I think we're stuck with removing them and sticking with the lowest common denominator of 5.0

**Comment by jdnoprada** [comment]
Nice, probably overlooked that part of the API. Thanks for this.

Too bad we can't do anything about it on OS5. Anyway, thanks for your support on the issue. Now I can rest assured to share this info to our client.

Good job!
