### ISSUE TITLE
HTML Select lists are no longer dismissed when the back key is trapped

### ISSUE THREAD

**Issue by jeffheifetz** [blackberry/WebWorks#88]
As documented in the forums here http://supportforums.blackberry.com/t5/Web-and-WebWorks-Development/SDK-2-3-Select-Lists/m-p/1505943#M19664

The new async dialogs (definitely select, probably also color and date) are not dismissed by the back button if the application grabs this event with a key listener.  

Also test the bbui sample application.  bbui traps the back button, but it seems to not navigate back screens when you hit the back button.  Investigate to see if this is an issue in bbui logic or if it is more fundamental.

**Comment by ranyodh** [comment]
Any update on when this bug is going to be fixed?

**Comment by kwallis** [comment]
Included in 2.3.1 release
