### ISSUE TITLE
Cannot set runOnStartup attribute of rim:background element to false

### ISSUE THREAD

**Issue by jeffheifetz** [blackberry/WebWorks#90]
What he ^ said.

As documented on the forums - http://supportforums.blackberry.com/t5/Web-and-WebWorks-Development/Invalid-config-xml-file-when-choosing-not-to-runOnStartup/m-p/1520737#M19862

**Comment by kwallis** [comment]
There are three tasks we probably want to tackle first:
1) Determine what the current logic in the code enforces
2) Find any existing documentation describing the intended behaviour of the rim:background element and the runOnStartup attribute
3) Validate the docs versus the code and determine correct behaviour.

Will ultimately have to go back to the forum post to update once we determine what the correct route forward is.

**Comment by kwallis** [comment]
cc @dmateescu

**Comment by jachoi** [comment]
Our documentation on Multiple Entry Points (MEP) indicates that the config file shown in the linked forum is indeed an invalid configuration.
Basically "rim:background" element specifies the background entry point for a widget and the "runOnStartup" attribute is used to determine whether or not the application should run when the device has start or when the application has been installed.

So in the case of config file shown in the forum, there is no need in specifying "rim:background" if the application will not be running in the background and instead it should just be <content src="index.html" />.

**Comment by jeffheifetz** [comment]
I don't think that explanation of "runOnStartup" can be correct. Obviously the app cannot be run before it has been installed, so the choice must be between startup and on invocation (from ribbon or another app).

At the moment the default value is true, and you are now claiming its invalid to specify false. In this case is the default value incorrect or does the attribute serve no purpose?

**Comment by jachoi** [comment]
Yes, the app cannot run before it has been installed, but it can run on install.

The default value of "runOnStartup" attribute is correct (default value is true) and it does serve a purpose when the developer wants to create a service widget.

**Comment by kwallis** [comment]
Could you not have a rim:background element that could be an invocation point from some other app/service/etc.?

**Comment by jachoi** [comment]
Yes you can have an app without rim:background element that can be invoked from other app/service/etc., but this application will run in the foreground.

**Comment by kwallis** [comment]
So we can confirm that only the foreground entry can be invoked by another service?  How does Push work?

----- Original Message -----

**Comment by jachoi** [comment]
We can also have background entry, if the app is configured to run in the background only. 

Or if we have rim:allowInvokeParams="true" attribute in the content element and then invoke the app with a specific entry point, the app will change to specified entry point and become visible.
