### ISSUE TITLE
blackberry 5.0 supported javascript framework 

### ISSUE THREAD

**Issue by chintan3100** [blackberry/WebWorks#92]
i am new in bb development

Any light weight Frame work you suggest for blackberry 5.0 ?
i am using jquery mobile(min) but it take lot of load in 5.0

**Comment by jeffheifetz** [comment]
I don't think this is really an issue, but the framework I'd suggest would be bbui- https://github.com/tneil/bbUI.js

**Comment by cdelcol** [comment]
Agreed. Please use the support forums for this type of question. You'll get far more information there.
http://supportforums.blackberry.com/t5/Web-and-WebWorks-Development/bd-p/browser_dev
